[serve.static]
env = "BUN_PUBLIC_*"

[test]
coverage = true
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]

[test.reporter]
junit = "unit.junit.xml"

[loader]
".ttf" = "file"
".otf" = "file"
".md" = "text"

[install]
registry = "https://registry.npmjs.org/"
