# =======================================
# DCS World Configuration
# =======================================
[dcs]
dcs_working_dir = "C:/Users/jonat/Saved Games/DCS.openbeta"                     # Path to DCS World working directory
dcs_install_dir = "D:/Program Files/Eagle Dynamics/DCS World OpenBeta"          # Path to DCS World installation directory

# =======================================
# Third Party Binaries Configuration
# =======================================
[binaries]
target_directory = ".bin"
wget = "binaries/wget.exe"          # Path to download the winget binary
sevenzip = "binaries/7za.exe"                                              # Path to 7zip executable

# =======================================
# Server Configuration
# =======================================
[server]
host = "0.0.0.0"   # Address to bind the HTTP server
port = 3001        # Port to listen on

# =======================================
# Logging Configuration (Pino)
# =======================================
[logging]
level = "debug"                  # Options: trace, debug, info, warn, error, fatal
#destination = "application.log"       # Optional file path or leave empty for console
colorize = false                 # Should log be colorized, set to true for better readability in terminal

# =======================================
# Database Configuration
# =======================================
[database]
url = "index.sqlite"      # Database URL