# =======================================
# Server Configuration
# =======================================
[server]
host = "0.0.0.0"   # Address to bind the HTTP server
port = 3001        # Port to listen on

# =======================================
# Logging Configuration (Pino)
# =======================================
[logging]
level = "debug"                  # Options: trace, debug, info, warn, error, fatal
#destination = "app.log"       # Optional file path or leave empty for console
colorize = false                 # Should log be colorized, set to true for better readability in terminal

# =======================================
# Database Configuration
# =======================================
[database]
url = "index.sqlite"      # Database URL

# =======================================
# Third Party Binaries Configuration
# =======================================
[binaries]
target_directory = ".bin"
wget = "https://eternallybored.org/misc/wget/1.21.4/64/wget.exe"          # Path to download the winget binary